spring:
    data:
        redis:
            host: localhost
            port: 10079
            timeout: 2000ms
            jedis:
                pool:
                    max-active: 8
                    max-wait: 3000ms
                    max-idle: 8
                    min-idle: 0
    cloud:
        kubernetes:
            discovery:
                enabled: false
        gateway:
            # For testing purpose.
            # After testing, the following configurations will be moved to application-staging.yaml & application.prod.yaml.
            routes:
                -   id: titan_treasure_route
                    uri: http://localhost:46258
                    predicates:
                        - Host=treasure.titan.com
                    filters:
                        - StripPrefix=1
                -   id: titan_gate_route
                    uri: http://localhost:32764
                    predicates:
                        - Host=gate.treasure.com
                    filters:
                        - StripPrefix=1

titan:
    gate:
        jwt-secret: q4~@x2uC$f@M2x*^e5&DB^L!3~)6@+
    treasure:
        login-url: http://127.0.0.1:3710/login
        default-home-url: http://127.0.0.1:3710/profile